stages:
  - matrix

Matrix:
  stage: matrix
  parallel:
    matrix:
      - images:
          - "acme-zynerone"
          - "clamd-zynerone"
          - "dockerapi-zynerone"
          - "dovecot-zynerone"
          - "netfilter-zynerone"
          - "olefy-zynerone"
          - "php-fpm-zynerone"
          - "postfix-zynerone"
          - "rspamd-zynerone"
          - "sogo-zynerone"
          - "solr-zynerone"
          - "unbound-zynerone"
          - "watchdog-zynerone"
          - "api-zynerone"
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/docker:stable
  before_script:
    - docker info
  script:
    - echo $DOCKERHUB_TOKEN | docker login --username $DOCKERHUB_USERNAME --password-stdin
    - cp helper-scripts/docker-compose.override.yml.d/BUILD_FLAGS/docker-compose.override.yml docker-compose.override.yml
    - docker compose build ${images}
    - docker compose push ${images}
