stages:
  - matrix

Matrix:
  stage: matrix
  image: ubuntu:latest
  parallel:
    matrix:
      - images:
          - "acme-zynerone"
          - "clamd-zynerone"
          - "dockerapi-zynerone"
          - "dovecot-zynerone"
          - "netfilter-zynerone"
          - "olefy-zynerone"
          - "php-fpm-zynerone"
          - "postfix-zynerone"
          - "rspamd-zynerone"
          - "sogo-zynerone"
          - "solr-zynerone"
          - "unbound-zynerone"
          - "watchdog-zynerone"
          - "api-zynerone"
  script:
    - apt install -y curl
    - curl -sSL https://get.docker.com/ | CHANNEL=stable sudo sh
    - service docker start
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cp helper-scripts/docker-compose.override.yml.d/BUILD_FLAGS/docker-compose.override.yml docker-compose.override.yml
    - docker compose build ${images}
    - docker compose push ${images}
