version: '2.1'
services:

    php-fpm-zynerone:
      volumes:
        - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

    sogo-zynerone:
      volumes:
        - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

    dovecot-zynerone:
      volumes:
        - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

    postfix-zynerone:
      volumes:
        - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

    acme-zynerone:
      volumes:
        - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

    watchdog-zynerone:
      volumes:
        - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

    api-zynerone:
      volumes:
        - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock

    mysql-zynerone:
      image: alpine:3.18
      command: /bin/true
      restart: "no"
