version: '2.1'
services:
  unbound-zynerone:
    build: ./data/Dockerfiles/unbound

  clamd-zynerone:
    build: ./data/Dockerfiles/clamd

  rspamd-zynerone:
    build: ./data/Dockerfiles/rspamd

  php-fpm-zynerone:
    build: ./data/Dockerfiles/phpfpm

  sogo-zynerone:
    build:
      context: ./data/Dockerfiles/sogo
      dockerfile: Dockerfile
      args:
        - SOGO_DEBIAN_REPOSITORY=http://packages.inverse.ca/SOGo/nightly/5/debian/

  dovecot-zynerone:
    build: ./data/Dockerfiles/dovecot

  postfix-zynerone:
    build: ./data/Dockerfiles/postfix

  acme-zynerone:
    build: ./data/Dockerfiles/acme

  netfilter-zynerone:
    build: ./data/Dockerfiles/netfilter

  watchdog-zynerone:
    build: ./data/Dockerfiles/watchdog

  dockerapi-zynerone:
    build: ./data/Dockerfiles/dockerapi

  solr-zynerone:
    build: ./data/Dockerfiles/solr

  olefy-zynerone:
    build: ./data/Dockerfiles/olefy

  api-zynerone:
    build: ./data/Dockerfiles/api