version: '2.1'
services:
  unbound:
    build: ./data/Dockerfiles/unbound

  clamd:
    build: ./data/Dockerfiles/clamd

  rspamd:
    build: ./data/Dockerfiles/rspamd

  php-fpm:
    build: ./data/Dockerfiles/phpfpm

  sogo:
    build:
      context: ./data/Dockerfiles/sogo
      dockerfile: Dockerfile
      args:
        - SOGO_DEBIAN_REPOSITORY=http://packages.inverse.ca/SOGo/nightly/5/debian/

  dovecot:
    build: ./data/Dockerfiles/dovecot

  postfix:
    build: ./data/Dockerfiles/postfix

  acme:
    build: ./data/Dockerfiles/acme

  netfilter:
    build: ./data/Dockerfiles/netfilter

  watchdog:
    build: ./data/Dockerfiles/watchdog

  dockerapi:
    build: ./data/Dockerfiles/dockerapi

  solr:
    build: ./data/Dockerfiles/solr

  olefy:
    build: ./data/Dockerfiles/olefy

  api:
    build: ./data/Dockerfiles/api