version: '2.1'
services:

    clamd:
      dns:
        - my.resolvers.ip.addr

    rspamd:
      dns:
        - my.resolvers.ip.addr

    php-fpm:
      dns:
        - my.resolvers.ip.addr

    sogo:
      dns:
        - my.resolvers.ip.addr

    dovecot:
      dns:
        - my.resolvers.ip.addr

    postfix:
      dns:
        - my.resolvers.ip.addr

    nginx:
      dns:
        - my.resolvers.ip.addr

    acme:
      dns:
        - my.resolvers.ip.addr

    watchdog:
      environment:
        - CHECK_UNBOUND=0
      dns:
        - my.resolvers.ip.addr

    dockerapi:
      dns:
        - my.resolvers.ip.addr

    api:
      dns:
        - my.resolvers.ip.addr