name: Build zynerone Docker Images

on:
  push:
    branches: [ "master", "staging" ]
  workflow_dispatch:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  docker_image_builds:
    strategy:
      matrix:
        images:
          - "acme-zynerone"
          - "clamd-zynerone"
          - "dockerapi-mailcow"
          - "dovecot-zynerone"
          - "netfilter-zynerone"
          - "olefy-mailcow"
          - "php-fpm-zynerone"
          - "postfix-zynerone"
          - "rspamd-zynerone"
          - "sogo-zynerone"
          - "solr-mailcow"
          - "unbound-zynerone"
          - "watchdog-zynerone"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker
        run: |
          curl -sSL https://get.docker.com/ | CHANNEL=stable sudo sh
          sudo service docker start
      - name: Prepair Image Builds
        run: |
          cp helper-scripts/docker-compose.override.yml.d/BUILD_FLAGS/docker-compose.override.yml docker-compose.override.yml
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.BACKUPIMAGEBUILD_ACTION_DOCKERHUB_USERNAME }}
          password: ${{ secrets.BACKUPIMAGEBUILD_ACTION_DOCKERHUB_TOKEN }}
      - name: Build Docker Images
        run: |
          docker compose build ${image}
          docker compose push ${image}
        env:
          image: ${{ matrix.images }}
